# Generated by Django 3.1.4 on 2020-12-22 11:21

from django.db import migrations, models
import timescale.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_auto_20201221_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('value', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelManagers(
            name='metric',
            managers=[
            ],
        ),
    ]
